# Generated by Django 4.2.2 on 2024-05-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('org_address', models.CharField(max_length=255)),
                ('nature_of_work', models.CharField(max_length=255)),
                ('reporting_authority', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('internship_mode', models.CharField(max_length=20)),
                ('stipend', models.CharField(default='Yes', max_length=4)),
                ('ppo', models.CharField(default='Yes', max_length=3)),
                ('status', models.CharField(max_length=100)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.student')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.faculty')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.student')),
            ],
        ),
    ]
