# Generated by Django 4.2.2 on 2024-06-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_id', models.CharField(max_length=100, unique=True)),
                ('register_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('alternate_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('organisation_name', models.CharField(max_length=255)),
                ('organisation_address_website', models.TextField()),
                ('nature_of_work', models.TextField()),
                ('repr_name', models.CharField(max_length=255)),
                ('repr_designation', models.CharField(max_length=255)),
                ('repr_email_id', models.EmailField(max_length=254)),
                ('repr_mobile_no', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], max_length=20)),
                ('mode_of_internship', models.CharField(choices=[('Virtual', 'Virtual'), ('Physical', 'Physical')], max_length=10)),
                ('stipend', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('offer_letter_submitted', models.BooleanField(default=False)),
                ('completion_certificate_submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
