# Generated by Django 4.2.2 on 2024-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_alter_internshipresponse_completion_certificate_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=100, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('organisation_name', models.CharField(max_length=255)),
            ],
        ),
    ]
