# Generated by Django 4.2.2 on 2024-06-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_od'),
    ]

    operations = [
        migrations.AlterField(
            model_name='od',
            name='register_number',
            field=models.CharField(max_length=100),
        ),
    ]
