# Generated by Django 4.2.2 on 2024-06-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0005_alter_od_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='od',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
