# Generated by Django 4.2.2 on 2024-06-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_od_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
